server.port=2085
# Applicationn context name
server.servlet.context-path=/multidatasource

# Oracle data source details
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/freepdb1
spring.datasource.username=system
spring.datasource.password=root
#spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver


# 2nd Oracle data source
spring.datasource.second.url=jdbc:oracle:thin:@localhost:1521/freepdb1
spring.datasource.second.username=system
spring.datasource.second.password=root
#spring.datasource.second.driver-class-name=oracle.jdbc.driver.OracleDriver
